/**
 * DYLANDE — Enterprise B2B
 * Projectos: mostrar método e contexto sem publicar resultados não validados.
 */
import { ArrowUpRight, FileText, LockKeyhole } from "lucide-react";
import { Link } from "wouter";
import { PageIntro } from "@/components/SiteLayout";
import WhatsAppButton from "@/components/WhatsAppButton";
import { siteConfig } from "@/lib/siteConfig";
const contexts = [["01","Operações empresariais","Gestão, facturação e stock","/media/IMG-20260901-WA0008.jpg"],["02","Hospitalidade e serviços","Fluxos digitais por sector","/media/IMG-20260901-WA0009.jpg"],["03","Produto digital","Experiências web e multi-dispositivo","/media/IMG-20260901-WA0010.jpg"]];
export default function Projects(){return <div className="inner-page projects-page"><div className="container"><PageIntro kicker="Projetos e contexto" title="Tecnologia pensada para entrar no trabalho real." text="Cada solução começa num problema concreto. Os estudos de caso completos serão publicados quando os detalhes, tecnologias e resultados forem validados com os respectivos clientes." /></div><section className="container case-grid">{contexts.map(([n,label,title,image])=><article className="case-card" key={n}><div className="case-media"><img loading="lazy" src={image} alt=""/><span>{n} · Contexto de solução</span></div><div className="case-copy"><span className="eyebrow">{label}</span><h2>{title}</h2><div className="case-meta"><span><b>Desafio</b>Por validar com o cliente</span><span><b>Estratégia</b>Construída à medida</span><span><b>Resultado</b>A publicar após validação</span></div><Link href="/contacto" className="text-link">Falar sobre um projeto <ArrowUpRight size={15}/></Link></div></article>)}</section><section className="container projects-safe"><LockKeyhole size={22}/><div><span className="eyebrow">Transparência comercial</span><h2>Um bom case study começa com informação verificável.</h2><p>{siteConfig.portfolio.note}</p><div className="projects-actions"><Link href="/contacto" className="button button-primary">Solicitar proposta <ArrowUpRight size={16}/></Link><WhatsAppButton label="Consultar pelo WhatsApp" message="Olá, gostaria de falar sobre um projecto tecnológico." /></div></div></section><section className="container document-note"><FileText size={19}/><p>Para conhecer a base de produto existente, consulte também o <a href="/media/dylande-soft-ux-ui.pdf" target="_blank" rel="noreferrer">guia visual UX/UI</a>.</p></section></div>}
